#!/bin/bash
set -euxo pipefail

API="http://$DIFFICALCY_HOST/api/calculators"

curl --fail --silent --show-error "$API" | jq

curl --fail --silent --show-error "$API/osu/info" | jq
curl --fail --silent --show-error "$API/osu/calculation?BeatmapId=diffcalc-test-osu" | jq
curl --fail --silent --show-error "$API/osu/calculation?BeatmapId=diffcalc-test-osu" | jq # Run twice to test caching
curl --fail --silent --show-error "$API/osu/calculation?BeatmapId=diffcalc-test-osu&Mods=HD,DT" | jq
curl --fail --silent --show-error -X POST "$API/osu/batch/calculation" \
  -H "Content-Type: application/json" \
  -d '[{"BeatmapId": "diffcalc-test-osu"}, {"BeatmapId": "diffcalc-test-osu", "Mods": [{"Acronym": "DT"}]}]' | jq
curl --fail --silent --show-error "$API/osu/beatmapdetails?BeatmapId=diffcalc-test-osu" | jq

curl --fail --silent --show-error "$API/taiko/info" | jq
curl --fail --silent --show-error "$API/taiko/calculation?BeatmapId=diffcalc-test-taiko" | jq
curl --fail --silent --show-error "$API/taiko/calculation?BeatmapId=diffcalc-test-taiko" | jq # Run twice to test caching
curl --fail --silent --show-error "$API/taiko/calculation?BeatmapId=diffcalc-test-taiko&Mods=HD,DT" | jq
curl --fail --silent --show-error -X POST "$API/taiko/batch/calculation" \
  -H "Content-Type: application/json" \
  -d '[{"BeatmapId": "diffcalc-test-taiko"}, {"BeatmapId": "diffcalc-test-taiko", "Mods": [{"Acronym": "DT"}]}]' | jq
curl --fail --silent --show-error "$API/taiko/beatmapdetails?BeatmapId=diffcalc-test-taiko" | jq

curl --fail --silent --show-error "$API/catch/info" | jq
curl --fail --silent --show-error "$API/catch/calculation?BeatmapId=diffcalc-test-catch" | jq
curl --fail --silent --show-error "$API/catch/calculation?BeatmapId=diffcalc-test-catch" | jq # Run twice to test caching
curl --fail --silent --show-error "$API/catch/calculation?BeatmapId=diffcalc-test-catch&Mods=HD,DT" | jq
curl --fail --silent --show-error -X POST "$API/catch/batch/calculation" \
  -H "Content-Type: application/json" \
  -d '[{"BeatmapId": "diffcalc-test-catch"}, {"BeatmapId": "diffcalc-test-catch", "Mods": [{"Acronym": "DT"}]}]' | jq
curl --fail --silent --show-error "$API/catch/beatmapdetails?BeatmapId=diffcalc-test-catch" | jq

curl --fail --silent --show-error "$API/mania/info" | jq
curl --fail --silent --show-error "$API/mania/calculation?BeatmapId=diffcalc-test-mania" | jq
curl --fail --silent --show-error "$API/mania/calculation?BeatmapId=diffcalc-test-mania" | jq # Run twice to test caching
curl --fail --silent --show-error "$API/mania/calculation?BeatmapId=diffcalc-test-mania&Mods=HD,DT" | jq
curl --fail --silent --show-error -X POST "$API/mania/batch/calculation" \
  -H "Content-Type: application/json" \
  -d '[{"BeatmapId": "diffcalc-test-mania"}, {"BeatmapId": "diffcalc-test-mania", "Mods": [{"Acronym": "DT"}]}]' | jq
curl --fail --silent --show-error "$API/mania/beatmapdetails?BeatmapId=diffcalc-test-mania" | jq
